
-- Seed drone accessory subcategory products
INSERT INTO public.products (slug, name, description, price_xaf, old_price_xaf, category, image_url, gallery_urls, benefits, specifications, box_contents, extra_details, stock, is_trending, is_promo, rating, reviews_count) VALUES
-- Moteurs
('moteur-brushless-2207-kv2400','Moteur Brushless 2207 KV2400','Moteur haute performance pour drones racing & freestyle 5 pouces.',18000,22000,'drone-moteurs','/placeholder.svg','{}','{"Couple élevé pour vols agressifs","Roulements céramiques durables","Compatible 5 pouces FPV"}','{"KV":"2400","Poids":"32g","Diamètre":"22mm","Hauteur":"7mm"}','{"1 moteur brushless","Visserie M3","Notice"}','Idéal pour les pilotes freestyle confirmés.',30,true,true,4.7,42),
('moteur-1408-kv3600','Moteur 1408 KV3600 Cinewhoop','Compact et silencieux pour cinewhoops.',14500,NULL,'drone-moteurs','/placeholder.svg','{}','{"Faible vibration","Réponse instantanée","Connecteurs prêts à souder"}','{"KV":"3600","Poids":"14g","Diamètre":"14mm"}','{"1 moteur","Vis"}','Parfait pour le vol indoor.',40,false,false,4.6,18),
('moteur-2806-kv1300','Moteur 2806 KV1300 Long Range','Couple massif pour drones cargo 7 pouces.',22000,NULL,'drone-moteurs','/placeholder.svg','{}','{"Endurance prolongée","Refroidissement optimisé"}','{"KV":"1300","Poids":"45g"}','{"1 moteur","Visserie"}','Recommandé pour le long range.',20,false,false,4.8,11),
-- Hélices
('helices-5043-tri-x4','Hélices 5043 Tri-pales (x4 paires)','Set de 4 paires d''hélices 5 pouces tri-pales.',4500,6000,'drone-helices','/placeholder.svg','{}','{"Polycarbonate ultra-résistant","Équilibrage usine","Couleurs vives haute visibilité"}','{"Diamètre":"5 pouces","Pas":"4.3","Pales":"3","Trou":"5mm"}','{"4 paires d''hélices","Pochette"}','Pack idéal pour pilotes réguliers.',120,true,true,4.7,88),
('helices-3018-bi-x8','Hélices 3018 Bi-pales (x8)','Lot de 8 hélices 3 pouces pour cinewhoop.',3500,NULL,'drone-helices','/placeholder.svg','{}','{"Silencieuses","Légères"}','{"Diamètre":"3 pouces","Pas":"1.8"}','{"8 hélices"}','Ré assortiment recommandé.',200,false,false,4.5,54),
('helices-7038-x4','Hélices 7038 Long Range (x4)','Hélices 7 pouces pour drones long range.',5500,NULL,'drone-helices','/placeholder.svg','{}','{"Excellente portance","Faible consommation"}','{"Diamètre":"7 pouces","Pas":"3.8"}','{"4 hélices"}','Optimisez votre autonomie.',60,false,false,4.6,21),
-- Batteries
('lipo-1500mah-4s','Batterie LiPo 1500mAh 4S 100C','Batterie haute décharge pour FPV racing.',12000,15000,'drone-batteries','/placeholder.svg','{}','{"Décharge 100C explosive","XT60 préinstallé","Cellules équilibrées"}','{"Capacité":"1500 mAh","Tension":"14.8V","Décharge":"100C","Poids":"180g"}','{"1 batterie LiPo","Sangle velcro"}','Stockez à 50% entre les vols.',50,true,true,4.8,67),
('lipo-2200mah-3s','Batterie LiPo 2200mAh 3S 60C','Polyvalente pour quads 4 à 5 pouces.',9500,NULL,'drone-batteries','/placeholder.svg','{}','{"Bonne autonomie","Cycle de vie long"}','{"Capacité":"2200 mAh","Tension":"11.1V"}','{"1 batterie"}','Convient aux pilotes amateurs.',80,false,false,4.5,33),
('chargeur-lipo-isdt-q6','Chargeur LiPo ISDT Q6 Nano','Chargeur intelligent 200W multi-chimies.',28000,32000,'drone-batteries','/placeholder.svg','{}','{"Charge rapide 8A","Écran couleur","Compatible LiPo / LiHV / NiMH"}','{"Puissance":"200W","Cellules":"1S-6S"}','{"1 chargeur","Câble XT60"}','Indispensable pour gérer vos packs.',35,false,true,4.9,45),
-- Télécommandes
('radio-radiomaster-tx16s','Radiocommande RadioMaster TX16S MkII','Radio multiprotocole avec gimbals Hall.',95000,110000,'drone-telecommandes','/placeholder.svg','{}','{"Gimbals Hall haute précision","Multiprotocole 4-en-1","Écran couleur 4.3 pouces"}','{"Canaux":"16","Protocoles":"CRSF, ELRS, FrSky","Batterie":"2x 18650"}','{"1 radio","Sangle","Câble USB-C"}','La référence open-source.',15,true,false,4.9,128),
('radio-jumper-t-pro','Radiocommande Jumper T-Pro V2 ELRS','Radio compacte ELRS pour pilotes nomades.',62000,NULL,'drone-telecommandes','/placeholder.svg','{}','{"ELRS 2.4GHz intégré","Format poche","Autonomie 8h"}','{"Canaux":"16","Protocole":"ELRS"}','{"1 radio","Câble"}','Idéale pour le micro et tinywhoops.',20,false,false,4.7,52),
('recepteur-elrs-nano','Récepteur ELRS Nano 2.4GHz','Récepteur ultra-léger pour micro drones.',6500,8000,'drone-telecommandes','/placeholder.svg','{}','{"Latence ultra-basse","Portée jusqu''à 20km","Poids plume"}','{"Poids":"0.7g","Fréquence":"2.4GHz"}','{"1 récepteur","Antennes"}','Compatible tous quads modernes.',150,false,true,4.8,76),
-- Caméras & nacelles
('camera-fpv-runcam-phoenix','Caméra FPV RunCam Phoenix 2','Caméra analogique légendaire.',16500,19000,'drone-cameras','/placeholder.svg','{}','{"WDR 1000TVL","Faible latence","Excellente plage dynamique"}','{"Capteur":"1/2 CMOS","Sortie":"PAL/NTSC"}','{"1 caméra","Câble"}','Standard du FPV freestyle.',45,true,true,4.8,91),
('camera-hd-gopro-hero11','Caméra HD GoPro Hero 11 Black','Capture cinématique 5.3K pour drones cargo.',280000,320000,'drone-cameras','/placeholder.svg','{}','{"5.3K à 60fps","HyperSmooth 5.0","Étanche IPX8"}','{"Résolution":"5.3K","Stabilisation":"HyperSmooth 5.0"}','{"1 GoPro","Batterie","Câble USB-C"}','Capturez des plans aériens pro.',10,false,true,4.9,210),
('nacelle-3-axes-storm32','Nacelle 3 axes Storm32','Stabilisation 3 axes pour caméras d''action.',45000,NULL,'drone-cameras','/placeholder.svg','{}','{"3 axes ultra-stables","Carte Storm32 incluse"}','{"Axes":"3","Charge":"max 200g"}','{"1 nacelle","Visserie","Notice"}','Améliorez vos prises de vue.',18,false,false,4.6,29)
ON CONFLICT (slug) DO NOTHING;
